### ISSUE TITLE
foo_midi internal version string reported to Foobar2000, not updated to beta version #.

### ISSUE THREAD

**Issue by MelchiorGaspar** [stuerp/foo_midi#10]
The current release is v2.8.3.1 
and the new beta is of course v2.8.4.0_beta01
but Foobar2000 is showing v2.8.3.1 in the components list.
so this is just a minor issue... 
lol ;-)

**Comment by stuerp** [comment]
Fixed in beta 2

**Comment by MelchiorGaspar** [comment]
ty
