### ISSUE TITLE
this midi seems cant play properly on secret sauce

### ISSUE THREAD

**Issue by freeaim** [stuerp/foo_midi#20]
https://github.com/stuerp/foo_midi/assets/11797565/cfccb9cd-75c5-4a59-8e61-7b144cac3714

same midi on bassmidi;

https://github.com/stuerp/foo_midi/assets/11797565/e54c1dac-623d-4057-ba5b-6db1ef413ed9
 
midi:

[DKC3-GBA_RockfaceRumble_v1-1.zip](https://github.com/stuerp/foo_midi/files/12385413/DKC3-GBA_RockfaceRumble_v1-1.zip)

on x86 1.6.16, tried 2.0 but seems same results

**Comment by stuerp** [comment]
I don't hear any problem with BASS MIDI nor with Secret Sauce on my setup. What exactly do you find wrong with that rendering?

**Comment by freeaim** [comment]
harmonica is played as piano in secret sauce

**Comment by stuerp** [comment]
Secret Sauce uses the GS instruments. This is a GM file.

**Comment by freeaim** [comment]
hmm
gm  flavor didnt help either, and
[魔王魂  村05.zip](https://github.com/stuerp/foo_midi/files/12385591/05.zip)
this seems plays fine though, assuming this is gm

**Comment by stuerp** [comment]
Both are GM and neither of them sends a GM Reset so I assume Secret Sauce defaults to the GS set.

**Comment by stuerp** [comment]
> hmm gm flavor didnt help either, and [魔王魂 村05.zip](https://github.com/stuerp/foo_midi/files/12385591/05.zip) this seems plays fine though, assuming this is gm

GM Flavor was a no-op. Don't know why. I re-enabled it but it does not change the result. Bank 0 is selected before playback starts. I'll have to dive into the byte stream. I'm intrigued.

**Comment by stuerp** [comment]
I can't find anything weird in the MIDI stream.
