### ISSUE TITLE
incorrect bass.dll version (2.4 is required)

### ISSUE THREAD

**Issue by nthmetaljustice** [stuerp/foo_midi#21]
After installation of the foo_midi plugin starting up foobar2000 shows a popup with this error:
incorrect bass.dll version (2.4 is required)
![grafik](https://github.com/stuerp/foo_midi/assets/81905573/f0037c6d-d21f-4940-b182-7d1ee1f6fa7f)
Initialization of the component then fails.

foo_midi has been taken from the foobar component webseite in version 2.9.0.0
I even tried to download bass.dll in version 2.4 from their website and make sure to use x86 version of that dll and replace it manually. Sadly that did not help either.

**Comment by stuerp** [comment]
Do you have an older bass.dll somewhere else on your drive that gets loaded before the one that comes with the component. It's obviously a BASSMIDI error message that is not generated by the component nor foobar2000 itself.

**Comment by stuerp** [comment]
No feedback from user.

**Comment by nthmetaljustice** [comment]
Actually you were correct, it was a bass.dll, but I needed process explorer to find it, thanks for providing the right hint.
