### ISSUE TITLE
v2.9.0.0 crashing almost instantly on amd x64

### ISSUE THREAD

**Issue by sunflowers33d** [stuerp/foo_midi#22]
updated to v2.9.0.0 and within about 5 seconds or so fb2k crashes, regardless of what i try to do or if i even interact with the app.
as a test i downloaded and installed v2.8.5.0, no crashing there
[failure_00000003.txt](https://github.com/stuerp/foo_midi/files/12680010/failure_00000003.txt)

**Comment by stuerp** [comment]
Looks like there is a MIDI file in your library that is corrupt. Any chance you can zero in on it; an possibly an .XMI or .XMF file since processing for those was updated in 2.9.0?

**Comment by sunflowers33d** [comment]
i have no idea what the file causing the issue could've been, but sure enough clearing the folders it searches for seems to have fixed the issue. thank you!

i don't have any XMI or (m)XMFs in the music folder it was scanning before so i'm really not sure what it could've been getting stuck on
