### ISSUE TITLE
Feature request: Allow using custom .wopl banks

### ISSUE THREAD

**Issue by Epictyphlosion** [stuerp/foo_midi#23]
I've noticed the plugin has DMXOPL already integrated for use with libADLMIDI, but only the GS version. There exists a version with patches for both GS and XG instruments on the project's github page, but I can't use it as there's no way to choose custom instrument banks from a file.

**Comment by stuerp** [comment]
I'll look into it.

**Comment by stuerp** [comment]
Am I right that this feature is currently not yet released (GENADLDATA_CUSTOM_BANKLIST) and that it is a compile-time feature? I'm not (yet) familiar with the inner workings of libADLMIDI. What is the use case for the several banks and how do they relate to GS/XG?

**Comment by Epictyphlosion** [comment]
> Does [2.9.1.0-alpha](https://github.com/stuerp/foo_midi/releases/tag/v2.9.1.0-alpha) work for you?

It works perfectly, thank you!

**Comment by stuerp** [comment]
Added to v2.9.1.3.
