### ISSUE TITLE
Invisible tick in checkboxes (custom theme)

### ISSUE THREAD

**Issue by d-bind** [stuerp/foo_midi#26]
I'm using a custom Windows 10 theme, with foobar in light mode, and since foo_midi v2.7.4.1 (that added dark mode support), the checkboxes look the same whether they're ticked or not. Previously they used a different-looking UI element.

If I switch foobar to dark mode, the check marks become visible against dark background, but I'd prefer to avoid foobar's dark mode. On paper, seems like light mode UI should have been unaffected by 2.7.4.1 changes, but I'm not sure if this is something under your control. Can you make the light mode use the old checkbox element?

Since this is basically a self-inflicted problem on my part, feel free to close this if it's a hassle.
But also: the text doesn't fit in the box since the UI reshuffle.

![2.7.4.0](https://github.com/stuerp/foo_midi/assets/104466974/b9bffaee-82de-48f4-9ac2-de8eb0fbe60e) ![2.9.1.3 light](https://github.com/stuerp/foo_midi/assets/104466974/c32916e7-3521-4c28-b9ec-55c3fc21259c) ![2.9.1.3 dark](https://github.com/stuerp/foo_midi/assets/104466974/16a70f10-4d91-4cc9-b3a4-00d267c80481)

**Comment by stuerp** [comment]
The dark mode is implemented by foobar2000 itself by hacking the theme and rendering code of all controls on a dialog. It takes one line of code to support it in a component. If I step away from that I'd have to reimplement all that code myself.
