### ISSUE TITLE
Unterminated strings in VST names

### ISSUE THREAD

**Issue by d-bind** [stuerp/foo_midi#27]
Since foo_midi v2.8.0.0, Roland VSTs show up with random garbage after their names, and the names themselves are incomplete.

Affects VSC 1.6, HyperCanvas 1.6, SCVA 1.1.6.

![2.7.4.2](https://github.com/stuerp/foo_midi/assets/104466974/77825b7b-f79a-4b21-b163-33c5069e97f4) ![2.9.1.3](https://github.com/stuerp/foo_midi/assets/104466974/669ddf73-35ec-4841-a9a7-1b46ed87b5a2)

**Comment by stuerp** [comment]
Thx for the bug report. I'll have a look later.

**Comment by stuerp** [comment]
I understand what's happening but not why.  The recent version of the plugin prefix all VSTi's with 'VSTi' and then append the vendor and/or product name. Since I don't have that VST it's kinda hard to debug.

**Comment by stuerp** [comment]
v2.16 has been released with a fix for the VSTi configuration not getting saved.
