### ISSUE TITLE
Converting with Secret Sauce player takes seemly forever when looping mode is set to "Loop and fade"

### ISSUE THREAD

**Issue by Dobby233Liu** [stuerp/foo_midi#28]
Testcase: [deoxynn hometown midi.zip](https://github.com/stuerp/foo_midi/files/13536352/deoxynn.hometown.midi.zip)

In this case, when Looping -> Other is set to "Never loop", conversion of the file (to Ogg Vorbis, q1.0, just in case) takes 3 seconds;
whereas when it's set to "Loop and fade when detected" or "Loop and fade always", it... just goes on. I don't know exactly how long it takes, I didn't wait for it to finish.

fb2k version: v2.1 2023-11-13 x86
scva version: v1.11
component version: v2.9.1.3

**Comment by stuerp** [comment]
Fixed in the next release.

**Comment by Dobby233Liu** [comment]
Fixed in v2.9.2.0 indeed
