### ISSUE TITLE
Can't convert MIDI files using Sound Canvas

### ISSUE THREAD

**Issue by sanmadjack** [stuerp/foo_midi#29]
I'm using the Roland Sound Canvas VST to try and convert MIDIs to FLAC file. When I attemp to do so I get dozens of these popping up:

![image](https://github.com/stuerp/foo_midi/assets/1385789/e28405da-8598-4fcf-ba72-15aef69ad9f9)

If I close them it eventually creates the flac files, but the instruments aren't right, there's more piano than there should be. Is there something I can do to gather some more debug information to help solve this?

I am able to convert fine using a Yamaha VST, it's just this Roland one that's having trouble. Playing the MIDI files through foobar with the SoundCloud VST works just fine, it's just when I'm trying to convert them to FLAC.

**Comment by stuerp** [comment]
I just tried to reproduce this, without success. Which platform (x86, x64), hich version of the VST, which FLAC output settings are you using?

**Comment by sanmadjack** [comment]
I ran another test and found an interesting data point. The conversion appears to be working if I only convert a single file. The error is appearing when I attempt to convert multiple files. I also noted that the VST settings I apply don't appear to be taking effect on playback or conversion. Specifically, the Sound Canvas VST has several "Map Modes" that represent different synths. If I change it to SC-55, when I play or convert it still sounds just like the SC-8850 map the VST defaults to. If I re-open the VST settings it still shows the map mode I last selected, but the sound doesn't change.

Here's what I'm using:

foobar2000 v2.0 x64
VST is Sound Canvas VA version 1.1.6
foo_midi v2.9.2.0 downloaded just today

Here is the MIDI settings screen:
![image](https://github.com/stuerp/foo_midi/assets/1385789/594c23fe-8a7b-4dea-a3c2-13a04c48d13c)

Here is the FLAC convert settings:
![image](https://github.com/stuerp/foo_midi/assets/1385789/d27a2e4d-6d5c-41f8-a726-38f42e16ee6e)

On a side note, is it possible to have the VST's settings panel associated with the playing instance open? I think it would be advantageous to be able to adjust settings on-the-fly during playback, especially if troubleshooting

**Comment by Dobby233Liu** [comment]
https://twitter.com/ReC98Project/status/1735499710310322666 suggests changing Convertor's thread count to 1

![image](https://github.com/stuerp/foo_midi/assets/28653235/fcb50a49-6757-4fc2-8784-d987bbafb869)

**Comment by sanmadjack** [comment]
This took care of my conversion issue. Thank you.
