### ISSUE TITLE
In version 2.8.0.0 incorrect resize of control's width

### ISSUE THREAD

**Issue by serg-rsp** [stuerp/foo_midi#3]
In plugin version 2.8.0.0 have incorrectly resized controls in config popup dialog (outside of dialog) in case of Win11 DPI scale not equal 100%. On the image I have Win11 DPI scaling = 125%
![image](https://user-images.githubusercontent.com/56299339/235459202-e9cfce0e-3fe6-4f46-ba8d-0d7e125aeb32.png)

**Comment by grimes2** [comment]
Happens also to me. This is a scaling problem (Windows 11 Scaling 125% DPI).

**Comment by stuerp** [comment]
Any ideas on how to fix it? A manifest does not work. Windows resources don't seem to scale automatically (even though we use Device Independent Units, <roll-eyes>) . Other components that use the full width of the dialog also have that problem (e.g. Open Lyrics)

**Comment by serg-rsp** [comment]
> Any ideas on how to fix it? A manifest does not work. Windows resources don't seem to scale automatically (even though we have to use Device Independent Units, "...rolls eyes...") . Other components that use the full width of the dialog also have that problem (e.g. Open Lyrics)

I am not a coder in C++.
Maybe here https://learn.microsoft.com/en-us/windows/win32/hidpi/declaring-managed-apps-dpi-aware
https://mariusbancila.ro/blog/2021/05/19/how-to-build-high-dpi-aware-native-desktop-applications/

An application can run with one of four different DPI awareness modes:

-     Unaware, views all displays as having 96 DPI
-     System, introduced in Windows Vista, views all displays as having the DPI value of the primary display
-     Per-Monitor, introduced in Windows 8.1, views the DPI of the display that the application window is primary located on. When the DPI changes, top-level windows are notified of the change, but there is no DPI scaling of any UI elements.
-     Per-Monitor V2, introduced in Windows 10 1703, similar to Per-Monitor, but support automatic scaling of non-client area, theme-drawn bitmaps in common controls, and dialogs.

**Comment by grimes2** [comment]
foobar2000 is system aware.

**Comment by serg-rsp** [comment]
A-HA the bug can be workaround if apply Win10 application settings - Compatibiltiy - > HiDpi -> "System"
![image](https://user-images.githubusercontent.com/56299339/235469278-df3cf065-62e2-4f2e-aa05-52b75bd326bf.png)

**Comment by grimes2** [comment]
Confirmed, but foobar2000 fonts are blurry now.

**Comment by stuerp** [comment]
Fixed it. Apparently the combination of font parameters in the resource is very specific. Trial and error gave me a combination that works with different DPI's. I'll release a fix and wait for feedback before I close the issue.

**Comment by grimes2** [comment]
Fix confirmed in 2.8.1.0. Thank you.

**Comment by stuerp** [comment]
Fixed in 2.8.1.0.
