### ISSUE TITLE
Possible Virus

### ISSUE THREAD

**Issue by Michelist** [stuerp/foo_midi#33]
I'm sorry to have to tell you this, but: 
According to this result: 
https://www.virustotal.com/gui/file/93e28bab767288c13ede2c9ff43448a4ff0513ff40fe144527d603f22ac9c302 
it is not impossible that your building environment is infested. In the meantime, Windows Defender is now bagging the file foo_midi.fb2k-component in version v2.9.2.0 too. 

In view of the reputation of the scanners reporting the find, I consider the infection to be very likely to exist, as my initial scan, immediately after I noticed the launch two days ago, was still completely without hits. If you had used a problematic build environment, like most free builders for EXE installers, these hits would have occurred two days ago.

Regards
Michelist

**Comment by stuerp** [comment]
Thanks for the report but it's a false positive.

**Comment by Michelist** [comment]
I'll wait and see. Almost no one is safe from being compromised these days. I do not believe, nor am I saying, that this is deliberate. 

Regards
Michelist

**Comment by stuerp** [comment]
Or you can just remove the vshost.exe files and loose VSTi support. It's not my fault that legit functionality is flagged as suspect.

**Comment by ramonsmits** [comment]
> Or you can just remove the vshost.exe files and loose VSTi support.

That is what I did:

1. Save file to folder that is excluded from scanning
2. Open the archive with for example 7zip
3. Delete the `*.exe` files in the root
4. Scan the archive and no threats are detected
