### ISSUE TITLE
Cofiguration Panel UI Elements Incorrectly Scaled

### ISSUE THREAD

**Issue by JWatersMeet** [stuerp/foo_midi#36]
When accessing the foo_midi configuration panel, the UI elements are incorrectly scaled at 175%, per the below.

![foo_midi](https://github.com/stuerp/foo_midi/assets/136824455/5f40f273-85dd-4e09-89ca-881f336385b3)
![foo_midi paths](https://github.com/stuerp/foo_midi/assets/136824455/d487a009-3a15-43c7-9f42-20be1e5c2c86)

Same is true for other scalings over 100%.

**Comment by stuerp** [comment]
@JWatersMeet ,

I'm afraid I can't do anything about that. The dialog has a fixed size and fb2k dictates the size of the preference page. I don't want to make the controls smaller than they already are. The scaling is done by Windows.

**Comment by JWatersMeet** [comment]
FYI, this is now fixed, and the dialogues are correctly scaled for High-DPI. I'm unsure whether it was a Foobar2000 update, a ColumnsUI update (which I think renders the panels?) or because of the latest release of foo_mini.

**Comment by stuerp** [comment]
Thx for letting me know but I didn't do anything. It's not ColumnsUI. The dialog is rendered using standard Windows functionality. I don't know what foo_mini does.
