### ISSUE TITLE
Invalid MIDI file: Bad SMF header track count

### ISSUE THREAD

**Issue by Chonkblonk** [stuerp/foo_midi#38]
I upgraded FooBar2000 and thus got the recent version of this MIDI plugin. Playing up a MIDI file which worked before, I get this error.

![bild](https://github.com/stuerp/foo_midi/assets/114463804/7c653e9e-9e18-408c-8be0-4902d9866f2e)

I'm not that deep into the technical aspects of MIDI, and Google didn't give me any relevant results (searching for "Bad SMF header track count" in quotation marks only turned up this page). I'm not necessarily asking for some kind of fix for this (though it did work in older versions), but maybe at least for the error code to give a clearer pointer towards what would need to be addressed in the file.

Here's a link to the MIDI itself:
https://www.vgmusic.com/music/console/nintendo/gamecube/Eternal_Darkness_Final_Boss.mid

**Comment by stuerp** [comment]
Depending on the MIDI file format the header of the file (SMF = Standard MIDI File format) is supposed to declare the number of MIDI tracks that are following the header,
The error message means that there is a mismatch with what the header declares and the data that followings. Or so the code thinks. I never rule out a coding error but after all these years I think most bugs have been found.

**Comment by Chonkblonk** [comment]
I see. Is there anything which I can do about this?
Optionally, if you know MIDI, are you able to see if there's anything which is quick and easy to fix with that file?

**Comment by stuerp** [comment]
I'll have a quick look to see if there is really something wrong with the file or if it is a bug. In case of the former you may try to load it into a MIDI editor that is more tolerant to errors in the file and resaved it. In case of the latter I guess I'll have to fix the bug :-)

**Comment by Chonkblonk** [comment]
Thanks, that's very kind of you!
For editing MIDI, do you have any suggestions? I tried looking at a MIDI program once, but I had no idea at all what I was looking at, and I have no idea what does what (nor any musical education lol).

**Comment by stuerp** [comment]
The file declares itself as a MIDI format 0 file but specifies a track count of 11. That is not possible according to the spec because a format 0 file should contain only 1 track with interleaved MIDI messages. I modified byte 10 in the file to make it a format 1 file. It now passes all the quality checks.
[Eternal_Darkness_Final_Boss.zip](https://github.com/stuerp/foo_midi/files/15174661/Eternal_Darkness_Final_Boss.zip)

**Comment by Chonkblonk** [comment]
Thank you very kindly for your assistance!

What program did you use to do this?

**Comment by stuerp** [comment]
Just a plain, old binary file editor: HxD (www.mh-nexus.de). If this is new territory for you, note that byte 10 is at offset 9 since byte numbering starts at 0.

**Comment by Chonkblonk** [comment]
Binary file editor? Like hex editing? I'm averse to complex math, and I always thought hex editing looked complex and hard to understand, so I think I would be better off trying to learn to tweak MIDI with a dedicated program.

Still, thank you for your help and accommodation!
