### ISSUE TITLE
Add support for Metaltech Battledrome *.HMP / Manually change playback speed

### ISSUE THREAD

**Issue by Jenetrix** [stuerp/foo_midi#40]
Metaltech Battledrome *.HMP files playback incorrectly, at roughly 2x the normal speed, in foo_midi compared to their Metaltech Earthsiege *.HMP counterparts. libADLMIDI also does not have the ES Expansion or BD soundbanks which are distinct compared to the stock ES one.

foo_midi 2.10.0.0, LibADLMIDI

see also: https://github.com/Wohlstand/libADLMIDI/issues/279

**Comment by stuerp** [comment]
Without a copy of the files it is hard to fix this.

**Comment by Jenetrix** [comment]
[ES Banks.zip](https://github.com/stuerp/foo_midi/files/15363482/ES.Banks.zip)
[ES Music.zip](https://github.com/stuerp/foo_midi/files/15363483/ES.Music.zip)
the games themselves have been freeware since 2015 so ill attach some examples here. contains *.hmp examples for all 3 as well as the sound banks.

**Comment by stuerp** [comment]
> [ES Banks.zip](https://github.com/stuerp/foo_midi/files/15363482/ES.Banks.zip) [ES Music.zip](https://github.com/stuerp/foo_midi/files/15363483/ES.Music.zip) the games themselves have been freeware since 2015 so ill attach some examples here. contains *.hmp examples for all 3 as well as the sound banks.

Thx. It seems the HMP/HMI don't have tempo information in them? Doubling the default tempo seems to fix the problem. I'll leave it like that for now.

https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha6

**Comment by Mohamed00** [comment]
Hi, this change caused issues with several HMP/HMI soundtracks. With this change, the soundtracks for games such as Descent, Descent 2 and Abuse now play at the wrong tempo. Here are some example files. 
[HMP.zip](https://github.com/stuerp/foo_midi/files/15366881/HMP.zip)
References for how these tracks are supposed to sound.
[Descent - game01.hmp](https://www.youtube.com/watch?v=YkM52T9HAwQ)
[Descent - Game02.hmp](https://www.youtube.com/watch?v=55mges6wGV4)
[Descent 2 - Game01.hmp](https://www.youtube.com/watch?v=soaUMdI0vNk)
[Abuse - ABUSE01.HMI](https://www.youtube.com/watch?v=B1zI10iAtq0&t=236s)

**Comment by stuerp** [comment]
foo_midi adds a hard-coded tempo track before converting the sequence. Any tempo information coming after that should overrule the default.

Is there a way, that you know of, to determine the 'correct' tempo?

If there is none letting the user override the default seems to be the only solution.

**Comment by stuerp** [comment]
@Jenetrix ,

The default tempo for HMI/HMP sequences can be configured in [alpha7](https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha7).

**Comment by Jenetrix** [comment]
Setting tempo to 80 and setting the Bank to HMI (Earthsiege) gets it most of the way there. The Battledrome and ES Expansion tracks still sound slightly off due to using the incorrect bank as those are not options.

**Comment by stuerp** [comment]
Is there a more recent version that supports the banks? I'd rather not patch the code myself.

**Comment by stuerp** [comment]
Released as v2.11.0.0.

**Comment by stuerp** [comment]
.
