### ISSUE TITLE
Support for some loops lost?

### ISSUE THREAD

**Issue by Mohamed00** [stuerp/foo_midi#41]
I noticed that in the latest foo_midi update, some loops that were previously supported no longer seem to be, such as those used in MIDI files from RPG maker. The loop info does exist, but isn't being acted on, and isn't being exposed in metadata, either. Here are some example files.
[broken loops.zip](https://github.com/stuerp/foo_midi/files/15279163/broken.loops.zip)

**Comment by stuerp** [comment]
ancient_castle has FF7 loop markers and should work. The others have RPG Maker markers but the loop gets removed because no Loop End was detected. Are you sure this is a new bug? The loop detection code hasn't been touched in a while.

**Comment by Mohamed00** [comment]
Yeah, this has been a thing for a while. Old versions of foo_midi use to handle the loop if a file with a loop start but no loop end was found. Looking further, the last version to handle this case was 2.8.4.0, and the files first broke with the release of 2.8.5.0. While it was broken, the loop info was still exposed, but with the release of 2.10.0.0, the loop info isn't being exposed in metadata, either.

**Comment by stuerp** [comment]
In one of the versions I did almost a rewrite of loop code because it was far too complex to maintain. I apparently broke some of the finer details of the loop modes.

**Comment by stuerp** [comment]
It should be fixed in https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha1

**Comment by Mohamed00** [comment]
All working, thanks!
