### ISSUE TITLE
Decoding settings page is cut off on high-DPI screens

### ISSUE THREAD

**Issue by nikitalita** [stuerp/foo_midi#43]
The settings pages are cut off and un-scrollable, not able to set all the settings:

<img width="741" alt="image" src="https://github.com/stuerp/foo_midi/assets/69168929/f6183776-0889-466a-98c9-fd23ea001b9d">
<img width="746" alt="image" src="https://github.com/stuerp/foo_midi/assets/69168929/6836610b-6265-43e8-9f95-1b86a0c3bbc1">

**Comment by stuerp** [comment]
That's a Wine problem and not something I can fix.

**Comment by nikitalita** [comment]
Uhm, this is present on Windows 11, too. See above.

**Comment by stuerp** [comment]
The dialog size is fixed by fb2k and the scaling is done by Windows itself. If you're using another DPI setting than 96 dpi you're out of luck. In the long term I plan to migrate some settings to dedicated pages but that is a boring and error prone task.

**Comment by nikitalita** [comment]
Ok. is there an issue to track that?

**Comment by stuerp** [comment]
Erh, I guess this one? I'll reopen it but it may take a while.

**Comment by stuerp** [comment]
> Erh, I guess this one? I'll reopen it but it may take a while.

I've tweaked the pages a little in [alpha7](https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha7).

**Comment by stuerp** [comment]
Released as v2.11.0.0.
