### ISSUE TITLE
LeapPad/Leapster MIDI loop support

### ISSUE THREAD

**Issue by BLiNXthetimesweeperGOD** [stuerp/foo_midi#45]
A ton of LeapFrog MIDIs recently got sent to me and I've been working on a recreation of the soundfont. Some of the MIDIs feel a bit incomplete without at least 1 loop, so it'd be nice to have support added for looping these.
The commands are the following:
Control 110 (sets the start of the loop and the loop count. The max loop count is 127.)
Control 111 (sets the end of the loop. Does nothing else.)
Some example MIDIs (and the work in progress soundfont so your ears don't get blasted with high pitched sounds on a few of these):
[LF MIDIs.zip](https://github.com/stuerp/foo_midi/files/15461781/LF.MIDIs.zip)

**Comment by BLiNXthetimesweeperGOD** [comment]
Oh, and the Match-A-Morphosis one (matchamorphisis.mid) desyncs on real hardware. If that MIDI has desync issues, that's normal.

**Comment by stuerp** [comment]
Have you looked at all the looping options? EMIDI/XMI are already supported.

**Comment by BLiNXthetimesweeperGOD** [comment]
I've mostly reverse engineered the SYN format they used on the Leapster and the locations of track commands 0x8E and 0x8F (both loop commands) line up perfectly with the locations of CC 110 and CC 111 in the source MIDIs.
Oh, and in case it's needed, here's a hardware capture of a full loop of one of these songs:
[matchamorphisisloop_Hardware.zip](https://github.com/stuerp/foo_midi/files/15468131/matchamorphisisloop_Hardware.zip)

**Comment by BLiNXthetimesweeperGOD** [comment]
Oh, one last thing I might've forgotten to mention:
Tracks loop independently of each other. I don't know if the other loops support this, but I tried it with the EMIDI ones (edited in over CC 110 and 111) and I'm pretty sure they all looped at the same time (despite one of the markers being moved as a test).

**Comment by stuerp** [comment]
Looping separate tracks is a sequencer-practice, not something you'd encounter in MIDI files. Besides the current engine does not support it: all tracks are merged into one stream of events.

**Comment by stuerp** [comment]
@BLiNXthetimesweeperGOD 

have a look at https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha8

**Comment by BLiNXthetimesweeperGOD** [comment]
Will do! Thanks.

**Comment by stuerp** [comment]
Released as v2.11.0.0.
