### ISSUE TITLE
(Feature Request) MIDI track muting?

### ISSUE THREAD

**Issue by jadasse** [stuerp/foo_midi#48]
Could there be a feature allowing me to mute certain tracks of the current MIDI playing? For instance, there should be 1-16 tracks a MIDI can play at once and I'd like to be able to mute at least one of them, sometimes. This feature is present in the Moondust Music Player [https://github.com/WohlSoft/Moondust-Project](url).

**Comment by stuerp** [comment]
That' should not be difficult to implement. The user interface will take the most work.

**Comment by jadasse** [comment]
> That' should not be difficult to implement. The user interface will take the most work.

I see, maybe make a separate tab like "Paths" and "Processing?"

**Comment by stuerp** [comment]
Implemented in v2.12.
