### ISSUE TITLE
Support for multimedia PC MIDI files?

### ISSUE THREAD

**Issue by Mohamed00** [stuerp/foo_midi#50]
Hi, I noticed that in 2.8.4.0, support was added for channel 16 drums, such as those appearing in Windows 3.0 MIDI files like CANYON.MID, PASSPORT.MID, etc. I've been doing some research on this, and it seems like files like this actually have two performances. Channels 1-10 are for sample based sound cards, while channels 13-16 are for FM synthesizers. It would be nice if the current support for channel 16 drums could be extended with an option to choose either the advanced GM performance on channels 1-10, or the basic performance on channels 13-16, perhaps with a multimedia PC mode checkbox.
Source: https://www.betaarchive.com/wiki/index.php?title=Microsoft_KB_Archive/84817 (scroll down to the Choosing Which Channels to Configure section).

**Comment by stuerp** [comment]
The extra drum channel started as a request accompanied with some example files and a disussion on the BASSMIDI forum. I didn't even realize CANYON.MID did something similar.
Maybe I can combine this with [this feature request](https://github.com/stuerp/foo_midi/issues/48).

**Comment by stuerp** [comment]
Implemented in v2.12.
