### ISSUE TITLE
Channel muting doesn't work properly with two or 3-port tracks

### ISSUE THREAD

**Issue by Mohamed00** [stuerp/foo_midi#52]
I noticed that when playing two or three-port MIDI files, the checkboxes to mute channels in preferences still only give access to channels 1-16. Multiport MIDI files themselves still seem to play fine, though. Example files: [multiport.zip](https://github.com/user-attachments/files/16571075/multiport.zip)

**Comment by stuerp** [comment]
Thx for the report. I did not implement port filtering yet.

**Comment by stuerp** [comment]
How do you see this implemented: filter the channel no matter which port it is sent to or allow the channels to be muted differently per port? The latter is more work, of course...

**Comment by Mohamed00** [comment]
Can you clarify what exactly you mean by "filter the channel no matter which port it is sent to?"

**Comment by stuerp** [comment]
I double-checked the code and I can't reproduce your issue.

To answer your question: the MIDI events are pre-processed when reading the file. The event data is packed into a 32-bit number with bit 25-30 containing the port number. The lower 4 bits contain the channel number and filtering is done using those bits. The port number is not looked at.

When I play your 2 example files with all channels disabled nothing passes.

**Comment by Mohamed00** [comment]
What I'm noticing is that in multiport files such as the ones shared here, the channel mute checkboxes still only list channels 1-16. It would be nice if this could be extended to also display channels 17-48,  so I could disable channels on specific MIDI ports.

**Comment by stuerp** [comment]
OK. So option 2 of my question. That poses a GUI problem because 'why stop at port 1?' MIDI allows up to 63 ports. I'll add a text box where the port number can be specified.

I also tweaked the code to send an All Notes Off channel mode message to stop playing notes.

**Comment by stuerp** [comment]
v2.13.0.0 allows the channels to be disabled per port.
