### ISSUE TITLE
Some option won't reset.

### ISSUE THREAD

**Issue by ghf50** [stuerp/foo_midi#59]
Hello, dear stuerp.
Some option won't reset when click "Reset page" button in Preference page.
foo_midi 2.14.0.0

on "MIDI Player" page, "BASS MIDI" --> "Volume"
on "MIDI Player" page, "Munt" --> "GM Set"
on "MIDI Player" --> "Processing" sub page, "Port number"

**Comment by stuerp** [comment]
Fixed in the next release.
