### ISSUE TITLE
Version 2.15 always forces BASSMIDI even if another player is slected

### ISSUE THREAD

**Issue by Mohamed00** [stuerp/foo_midi#63]
I noticed that with version 2.15, foo_midi is always forcing BASSMIDI to be used, even if I select another player such as LibADLMIDI or Secret Sauce. It seems that BASSMIDI and FluidSynth are the only players that work when selected, and clicking reset page has no effect.

**Comment by stuerp** [comment]
Thx for reporting. Also reported on the support forum. I'm release ASAP a fix.

**Comment by ghf50** [comment]
I'm encountered this issue too. When I select the player to "Super Munt GM", it still use BASSMIDI to play midi until I remove the "SoundFont" path in "Paths" sub page.

**Comment by stuerp** [comment]
Fixed in 2.15.1.
