### ISSUE TITLE
BASSMIDI Resampling option greyed out until reopen preference window.

### ISSUE THREAD

**Issue by ghf50** [stuerp/foo_midi#64]
When you switch Player to BASSMIDI from other player, the option "BASS MIDI" --> "Resampling" is greyed out and unavailable until you close the preference window and reopen it.
![BASSMIDI](https://github.com/user-attachments/assets/b60cd94d-3459-466d-9782-17cef2342d10)

When you switch Player to libADLMIDI from other player, the option "BASS MIDI" --> "Resampling" will be available immediately until you close the preference window and reopen it. 
![ADL](https://github.com/user-attachments/assets/714ea622-34d5-471b-b167-60a320c4b8e7)

version 2.15.0.0

**Comment by stuerp** [comment]
Thx for catching and reporting it. Fixed in 2.15.1.

**Comment by ghf50** [comment]
Really efficient. Thank you, stuerp.
