### ISSUE TITLE
BASSMIDI / FluidSynth is not working

### ISSUE THREAD

**Issue by BreakinBenny** [stuerp/foo_midi#7]
Heya! Why does the BASSMIDI player not let me configure it, nor choose a soundfont I'd like to utilize? I am using the latest current version of Foobar2000 64-bit thus far.
![image](https://github.com/stuerp/foo_midi/assets/4566768/612e0727-9895-4263-9601-abadb4e53e68)

EDIT: Having to choose from a separate Paths tab is weird, but I managed to fix the issue.

**Comment by stuerp** [comment]
It may be weird but before you had to set the path in the Advanced settings.
