### ISSUE TITLE
BASSMIDI: soundfont selection disappeared?

### ISSUE THREAD

**Issue by Cai0407** [stuerp/foo_midi#9]
Since v2.8, soundfont selection seems to be gone.

v2.7.4.4 (in FluidSynth section)
![BASSMIDI 2 7 4 4](https://github.com/stuerp/foo_midi/assets/2016274/4590e598-a195-4fef-bd7d-218c37069b88)
v2.8.3.1 (no menu in SoundFont section, even though the soundfont seems to be set as same as v2.7.4.4, same cached size, same actual output sound)
![BASSMIDI 2 8 3 1](https://github.com/stuerp/foo_midi/assets/2016274/7ab16bdb-341b-4eec-90b1-c23b88965c9b)

**Comment by stuerp** [comment]
All the paths have moved to a sub-menu called "Paths".

**Comment by Cai0407** [comment]
> All the paths have moved to a sub-menu called "Paths".

Oh, I missed it! Thanks!
